package ma.ensa.model;

// Generated 2 janv. 2016 00:44:40 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * User generated by hbm2java
 */
@Entity
@Table(name = "user", catalog = "ql")
public class User implements java.io.Serializable {

	private String login;
	private String pwd;
	private boolean active;
	private int montantTotale;
	private String nom;
	private String prenom;
	private Set<Roles> roleses = new HashSet<Roles>(0);

	public User() {
	}

	public User(String login, String pwd, boolean active, int montantTotale,
			String nom, String prenom) {
		this.login = login;
		this.pwd = pwd;
		this.active = active;
		this.montantTotale = montantTotale;
		this.nom = nom;
		this.prenom = prenom;
	}

	public User(String login, String pwd, boolean active, int montantTotale,
			String nom, String prenom, Set<Roles> roleses) {
		this.login = login;
		this.pwd = pwd;
		this.active = active;
		this.montantTotale = montantTotale;
		this.nom = nom;
		this.prenom = prenom;
		this.roleses = roleses;
	}

	@Id
	@Column(name = "login", unique = true, nullable = false, length = 40)
	public String getLogin() {
		return this.login;
	}

	public void setLogin(String login) {
		this.login = login;
	}

	@Column(name = "pwd", nullable = false, length = 40)
	public String getPwd() {
		return this.pwd;
	}

	public void setPwd(String pwd) {
		this.pwd = pwd;
	}

	@Column(name = "active", nullable = false)
	public boolean isActive() {
		return this.active;
	}

	public void setActive(boolean active) {
		this.active = active;
	}

	@Column(name = "montant_totale", nullable = false)
	public int getMontantTotale() {
		return this.montantTotale;
	}

	public void setMontantTotale(int montantTotale) {
		this.montantTotale = montantTotale;
	}

	@Column(name = "nom", nullable = false, length = 30)
	public String getNom() {
		return this.nom;
	}

	public void setNom(String nom) {
		this.nom = nom;
	}

	@Column(name = "prenom", nullable = false, length = 30)
	public String getPrenom() {
		return this.prenom;
	}

	public void setPrenom(String prenom) {
		this.prenom = prenom;
	}

	@OneToMany(fetch=FetchType.EAGER, mappedBy = "user")
	public Set<Roles> getRoleses() {
		return this.roleses;
	}

	public void setRoleses(Set<Roles> roleses) {
		this.roleses = roleses;
	}

}
